# TCL File Generated by Component Editor 15.0
# Tue Dec 05 15:42:06 CST 2017
# DO NOT MODIFY


# 
# AVL_INTERFACE "AVL_INTERFACE" v1.0
#  2017.12.05.15:42:06
# Hardware software interface
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module AVL_INTERFACE
# 
set_module_property DESCRIPTION "Hardware software interface"
set_module_property NAME AVL_INTERFACE
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ECE 385 Custom IPs"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME AVL_INTERFACE
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_interface.sv SYSTEM_VERILOG PATH avalon_interface.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_interface.sv SYSTEM_VERILOG PATH avalon_interface.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point AES_SLAVE
# 
add_interface AES_SLAVE avalon end
set_interface_property AES_SLAVE addressUnits WORDS
set_interface_property AES_SLAVE associatedClock CLK
set_interface_property AES_SLAVE associatedReset RESET
set_interface_property AES_SLAVE bitsPerSymbol 8
set_interface_property AES_SLAVE burstOnBurstBoundariesOnly false
set_interface_property AES_SLAVE burstcountUnits WORDS
set_interface_property AES_SLAVE explicitAddressSpan 0
set_interface_property AES_SLAVE holdTime 0
set_interface_property AES_SLAVE linewrapBursts false
set_interface_property AES_SLAVE maximumPendingReadTransactions 0
set_interface_property AES_SLAVE maximumPendingWriteTransactions 0
set_interface_property AES_SLAVE readLatency 0
set_interface_property AES_SLAVE readWaitStates 0
set_interface_property AES_SLAVE readWaitTime 0
set_interface_property AES_SLAVE setupTime 0
set_interface_property AES_SLAVE timingUnits Cycles
set_interface_property AES_SLAVE writeWaitTime 0
set_interface_property AES_SLAVE ENABLED true
set_interface_property AES_SLAVE EXPORT_OF ""
set_interface_property AES_SLAVE PORT_NAME_MAP ""
set_interface_property AES_SLAVE CMSIS_SVD_VARIABLES ""
set_interface_property AES_SLAVE SVD_ADDRESS_GROUP ""

add_interface_port AES_SLAVE AVL_ADDR address Input 4
add_interface_port AES_SLAVE AVL_CS chipselect Input 1
add_interface_port AES_SLAVE AVL_READ read Input 1
add_interface_port AES_SLAVE AVL_READDATA readdata Output 16
add_interface_port AES_SLAVE AVL_WRITE write Input 1
add_interface_port AES_SLAVE AVL_WRITEDATA writedata Input 16
set_interface_assignment AES_SLAVE embeddedsw.configuration.isFlash 0
set_interface_assignment AES_SLAVE embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AES_SLAVE embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AES_SLAVE embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Export_Data
# 
add_interface Export_Data conduit end
set_interface_property Export_Data associatedClock CLK
set_interface_property Export_Data associatedReset RESET
set_interface_property Export_Data ENABLED true
set_interface_property Export_Data EXPORT_OF ""
set_interface_property Export_Data PORT_NAME_MAP ""
set_interface_property Export_Data CMSIS_SVD_VARIABLES ""
set_interface_property Export_Data SVD_ADDRESS_GROUP ""

add_interface_port Export_Data EXPORT_COORDS EXPORT_COORDS Output 16
add_interface_port Export_Data EXPORT_DIRECT EXPORT_DIRECT Output 16
add_interface_port Export_Data EXPORT_ENCOUNT EXPORT_ENCOUNT Output 16
add_interface_port Export_Data EXPORT_CURPOKE EXPORT_CURPOKE Output 16
add_interface_port Export_Data EXPORT_HEALTH EXPORT_HEALTH Output 16

